### ISSUE TITLE
opengis.referencing.NoSuchAuthorityCodeException during Osm2MultimodalNetwork.run

### ISSUE THREAD

**Issue by kensongzhu** [matsim-org/pt2matsim#135] opened 2021-03-29 23:52 UTC
Hello everyone,

I gave a try today with pt2matsim and am getting the error as described in title. 

### Java Version

```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```

### Matsim Versions 

- matsim: **12.0**
- pt2matsim: **21.1**

### My code 

```java
String inputOsmConfigFile = "original-input-data/config/osm.xml";
OsmConverterConfigGroup osmConfig = OsmConverterConfigGroup.loadConfig(inputOsmConfigFile);
Osm2MultimodalNetwork.run(osmConfig);
````

### Error

```
2021-03-30T01:25:01,937  INFO Counter:74 relation 2693
2021-03-30T01:25:02,440  WARN MGC:174 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
2021-03-30T01:25:02,838  INFO FrameworkLogger:-1 dataFileCache open start
2021-03-30T01:25:02,985  WARN MGC:174 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
Exception in thread "main" java.lang.IllegalArgumentException: org.opengis.referencing.NoSuchAuthorityCodeException: No code "EPSG:8682" from authority "European Petroleum Survey Group" found for object of type "CoordinateReferenceSystem".
	at org.matsim.core.utils.geometry.geotools.MGC.getCRS(MGC.java:177)
	at org.matsim.core.utils.geometry.transformations.GeotoolsTransformation.<init>(GeotoolsTransformation.java:57)
	at org.matsim.core.utils.geometry.transformations.TransformationFactory.getCoordinateTransformation(TransformationFactory.java:80)
	at org.matsim.pt2matsim.osm.OsmMultimodalNetworkConverter.convert(OsmMultimodalNetworkConverter.java:107)
	at org.matsim.pt2matsim.run.Osm2MultimodalNetwork.run(Osm2MultimodalNetwork.java:87)
	at org.matsim.project.RunNetworkAndTransitSchedule.main(RunNetworkAndTransitSchedule.java:33)
Caused by: org.opengis.referencing.NoSuchAuthorityCodeException: No code "EPSG:8682" from authority "European Petroleum Survey Group" found for object of type "CoordinateReferenceSystem".
	at org.geotools.referencing.factory.AbstractAuthorityFactory.noSuchAuthorityCode(AbstractAuthorityFactory.java:874)
	at org.geotools.referencing.factory.epsg.DirectEpsgFactory.createCoordinateReferenceSystem(DirectEpsgFactory.java:2239)
	at org.geotools.referencing.factory.BufferedAuthorityFactory.createCoordinateReferenceSystem(BufferedAuthorityFactory.java:731)
	at org.geotools.referencing.factory.AuthorityFactoryAdapter.createCoordinateReferenceSystem(AuthorityFactoryAdapter.java:779)
	at org.geotools.referencing.factory.BufferedAuthorityFactory.createCoordinateReferenceSystem(BufferedAuthorityFactory.java:731)
	at org.geotools.referencing.factory.AuthorityFactoryAdapter.createCoordinateReferenceSystem(AuthorityFactoryAdapter.java:779)
	at org.geotools.referencing.factory.FallbackAuthorityFactory.createCoordinateReferenceSystem(FallbackAuthorityFactory.java:624)
	at org.geotools.referencing.factory.AuthorityFactoryAdapter.createCoordinateReferenceSystem(AuthorityFactoryAdapter.java:779)
	at org.geotools.referencing.factory.ThreadedAuthorityFactory.createCoordinateReferenceSystem(ThreadedAuthorityFactory.java:635)
	at org.geotools.referencing.DefaultAuthorityFactory.createCoordinateReferenceSystem(DefaultAuthorityFactory.java:176)
	at org.geotools.referencing.CRS.decode(CRS.java:533)
	at org.matsim.core.utils.geometry.geotools.MGC.getCRS(MGC.java:175)
```

### Quesion 

Somehow I managed to fix it by adding **gt-referencing** and **gt-epsg-hsql** explicitly
to the **pom.xml** with version **24.2**,  the current one **21.5** that comes with matsim doesn't work for me.
But why? Any help or explaination would be appreciated.

```xml
  <properties>
    <geotools.version>24.2</geotools.version>
 </properties>

 <dependencies>
      <dependency>
            <groupId>org.geotools</groupId>
            <artifactId>gt-referencing</artifactId>
            <version>${geotools.version}</version>
        </dependency>
        <dependency>
            <groupId>org.geotools</groupId>
            <artifactId>gt-epsg-hsql</artifactId>
            <version>${geotools.version}</version>
        </dependency>
 </dependencies>
```

**Comment by polettif** [comment] 2021-03-30 09:28
Thanks for your nicely formatted issue.

It looks like "EPSG:8682" was not part of gt-epsg-hsql 21.5 and has been added since. [epsg.io](https://epsg.io/8682) lists 2019-07-17 as a revision date.

Your fix suggests that this should be resolved by upgrading the geotools version in pt2matsim.

**Comment by kensongzhu** [comment] 2021-03-30 11:39
@polettif Thanks for your quick response.  

However, one still can not come into the conclusion that the revision date is the indicator to tell if upgrading geotools is needed, since geotools **21.5** was released later in Feb, 2020. Unfortunately, I couldn't find any information about what epsg are included or updated  in each release under geotools.   

Besides, just my personal wish, it would be nice that **pt2matsim** has a trouble shooting section somewhere to cover common issues like this, since anyone can easily start with any epsg code that is not included in an older version of geotools,  which is currently included by **matsim** itself.

**Comment by polettif** [comment] 2021-03-31 15:41
Looks like my initial reaction was pretty off base. I can't reproduce the issue, I added a [minimal test](https://github.com/matsim-org/pt2matsim/commit/c8959cae8e20fb41fde55ee11f481f41a9a1315c) and it works on my machine and [with actions](https://github.com/matsim-org/pt2matsim/runs/2238311102).

This issue might be related to #134. So there might be a problem with the project setup or there's an issue with pt2matsim and matsim dependencies clashing.

Your suggestion for a troubleshooting section sounds good, there's already some notes on coordinate systems in the wiki, should be easy to expand on that. Also, it could be pointed out in the readme. However, I'm not yet sure what the fix for this issue is.

**Comment by sebhoerl** [comment] 2021-03-31 16:56
Are you running this from a packaged jar or directly in some IDE? In the former case there may be some issues with packaging jar contents and you will need to use some transformers in Maven. How are you using the code?

Also, this error is common (in earlier versions of geotools) when Java cannot override the temporary files created in `/tmp` by Geotools where the reference systems are unpackged temporarily during run time. We often had this problem when we were running multiple users on one system. Then one user would create `/tmp/Geotools`, the simulation or the code would crash and the folder would remain there. Now when the second user tried to run geotools, there would be such an error as you have shown, because the folder was still there and created under the first user (so the second could not delete it).

If it is on linux you can check `ls -o /tmp/Geotools` or `ls -/tmp/geotools` something like that (not sure what was the exact name). In this case, the fix is to define explicitly an independent tmp Path before you run the code, so Java doesn't use the global `/tmp`. But also, I think they have fixed in the later geotools versions now by randomizing the name of the temporary created geotools folder.

Is one of these two cases relevant to you?

**Comment by kensongzhu** [comment] 2021-03-31 22:00
@polettif 
The minimal test provided doesn't trigger any CRS calls, it seems to me that it just sets the outputCRS then reads the osm file into buffer

Since the error is raised at **org.matsim.core.utils.geometry.geotools.MGC.getCRS** , following test fails with same error on my side if geotools **21.5** is applied.

```java
import org.junit.Assert;
import org.junit.Test;
import org.matsim.core.utils.geometry.geotools.MGC;
import org.opengis.referencing.crs.CoordinateReferenceSystem;

public class RunMGCTest {
    
    @Test
    public void test(){
        CoordinateReferenceSystem targetCRS = MGC.getCRS("EPSG:8682");
        Assert.assertNotNull(targetCRS);
    }
}
```

So I guess,  the EPSG code is just not there as you initially suggested.

@sebhoerl I currently runs through Intellij but eventually I will package it into jar. 
I checked that `/tmp/GeoTools` is there with or without manually adding geotools stuff to `pom.xml`.   
Anyway, thank you for pointing  this out and I will keep it in mind if it hits me later. 

I am having the same issue as #134 and thought it was the reason. Now it seems to me that it is irrelevant

**Comment by polettif** [comment] 2021-04-01 07:07
> The minimal test provided doesn't trigger any CRS calls, it seems to me that it just sets the outputCRS then reads the osm file into buffer

Sorry, you're right, I completely forgot the actual conversion.

The PR should fix this issue, EPSG:8682 seems to be unaviable with the geotools version in MATSim (21.5). I'll stop guessing further 😄

**Closed** 2021-04-07 06:45 UTC
